keys:
  - &evergarden_kurisu age154ausyv0u0lscdxlurm29wnktw0w694z6q87xnd5l5laj2xrp98qrkxc74

  - &shiina age14hkf8s68chh57vt78mmpt8trghsa29kdalgrp7lp6fvkm8ghautqw39xgw
  - &shiina_kurisu age183sga8rlttn0ckepytprkudhsaykr7ksn9rv0xkekrvadymx63xqed2ytq

creation_rules:
  - path_regex: secrets/users/kurisu.yaml
    key_groups:
      - age:
          # Users
          - *evergarden_kurisu
          - *shiina_kurisu
          # Hosts
          - *shiina
  - path_regex: secrets/hosts/shiina.yaml
    key_groups:
      - age:
          # Users
          - *evergarden_kurisu
          - *shiina_kurisu
          # Hosts
          - *shiina
