keys:
  - &evergarden_kurisu age154ausyv0u0lscdxlurm29wnktw0w694z6q87xnd5l5laj2xrp98qrkxc74

  - &shiina age1q5827wzudne3fsh0t5xfhm7axtmxctfkx8t2ruthlddvcrnetdkskh9gk8
  - &shiina_kurisu age1qyf4mggsysyv5njtmk8pvrmf56l82qysxxkrfawaqa80l0ewhvtqt5367q

creation_rules:
  - path_regex: secrets/users/kurisu.yaml
    key_groups:
      - age:
          # Users
          - *evergarden_kurisu
          - *shiina_kurisu
          # Hosts
          - *shiina
  - path_regex: secrets/hosts/shiina.yaml
    key_groups:
      - age:
          # Users
          - *evergarden_kurisu
          - *shiina_kurisu
          # Hosts
          - *shiina
