on:
  pull_request:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v5
      - run: nix flake metadata
      - run: nix flake check
      - run: nix build .#nixosConfigurations.shiina.config.system.build.toplevel
      - run: nix build .#shiina-vm
